# Numpy Basics

In [ ]:
import numpy as np

## Creating arrays

In [ ]:
my_list = [1, 2, 3]
type(my_list)

list

In [ ]:
my_array = np.array(my_list)
type(my_array)

numpy.ndarray

## Other methods to create arrays

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.random.seed(57)
np.random.randint(0, 100, 10)

array([79, 86,  5, 22, 79, 98, 56, 40, 81, 37])

## Some useful methods

In [ ]:
arr = np.array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [ ]:
arr.max()

95

In [ ]:
arr.argmax()

0

In [ ]:
arr.min()

9

In [ ]:
arr.argmin()

7

In [ ]:
arr.mean()

60.8

In [ ]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

## Indexing

In [ ]:
mat = np.arange(0, 40).reshape(4, 10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
mat[2, 7]

27

In [ ]:
mat[:, 1]

array([ 1, 11, 21, 31])

In [ ]:
mat[3, :]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
mat[1:3, 2:7]

array([[12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26]])