# Numpy Basics

NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

[NumPy: The absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)

## Importing

To access NumPy and its functions import it in your Python code like this:

In [1]:
import numpy as np

We shorten the imported name to np for better readability of code using NumPy. This is a widely adopted convention that you should follow so that anyone working with your code can easily understand it.

## Creating Arrays

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

### How to create a basic array

To create a NumPy array, you can use `np.array` function.

---

`np.array(Array-like object, int dtype=None, bool copy=True, char order='K', bool subok=False, int ndmin=0, Array-like like=None))`

**Description:** Create an array.

**Parameters:**

`object`: An array, any object exposing the array interface, an object whose \_\_array\_\_ method returns an array, or any (nested) sequence. If object is a scalar, a 0-dimensional array containing object is returned.

`dtype`: The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence

* `int8`: Integer (-128 to 127)
* `uint8`: Unsigned integer (0 to 255)
* `float32`: Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
* and some more...

`copy`: If true (default), then the object is copied. Otherwise, a copy will only be made if \_\_array\_\_ returns a copy, if obj is a nested sequence, or if a copy is needed to satisfy any of the other requirements

`order`: {‘K’, ‘A’, ‘C’, ‘F’}. Specify the memory layout of the array. If object is not an array, the newly created array will be in C order (row major) unless ‘F’ is specified, in which case it will be in Fortran order (column major). If object is an array the following holds.

`subok`: If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array 

`ndmin`: Specifies the minimum number of dimensions that the resulting array should have. Ones will be prepended to the shape as needed to meet this requirement.

`like`: Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the \_\_array_function\_\_ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.


**Return Value:** An array object satisfying the specified requirements.

---

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

### Other methods to create arrays

`np.zeros`: Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s.

---

`np.zeros(Tuple shape, int dtype=np.float64, char order='C', Array-like like=None)`

**Description:** Return a new array of given shape and type, filled with zeros.

**Parameters:**

`shape`: Shape of the new array

`dtype`: The desired data-type for the array

`order`: {‘C’, ‘F’}. Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

`like`: Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the \_\_array_function\_\_ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

**Return Value:** Array of zeros with the given shape, dtype, and order.

---


In [3]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

`np.ones`: An array filled with 1’s.

---

`np.ones(Tuple shape, int dtype=np.float64, char order='C', Array-like like=None)`

**Description:** Return a new array of given shape and type, filled with ones.

**Parameters:**

`shape`: Shape of the new array

`dtype`: The desired data-type for the array

`order`: {‘C’, ‘F’}. Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

`like`: Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the \_\_array_function\_\_ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

**Return Value:** Array of ones with the given shape, dtype, and order.

---


In [4]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

`np.arange()`: You can create an array with a range of elements.

---

`np.arange([float start=0, float stop, float step=1, int dtype=None, Array-like like=None)`

**Description:** Return evenly spaced values within a given interval.

**Parameters:**

`start`: Start of interval. The interval includes this value. 

`stop`: End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

`step`: Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

`dtype`: The type of the output array. If dtype is not given, infer the data type from the other input arguments.

`like`: Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the \_\_array_function\_\_ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

**Return Value:** Array of evenly spaced values.

---

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`np.linspace()`: You can create an array with values that are spaced linearly in a specified interval.

---

`numpy.linspace(float start, float stop, int num=50, bool endpoint=True, bool retstep=False, int dtype=None, int axis=0)`

**Description:** Return evenly spaced numbers over a specified interval.

**Parameters:**

`start`: The starting value of the sequence.

`stop`: The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples, so that stop is excluded. Note that the step size changes when endpoint is False.

`num`: Number of samples to generate.

`endPoint`: If True, stop is the last sample.

`retstep`: If True, return (samples, step), where step is the spacing between samples.

`dtype`: The type of the output array. If dtype is not given, the data type is inferred from start and stop. The inferred dtype will never be an integer; float is chosen even if the arguments would produce an array of integers.

`axis`: The axis in the result to store the samples. Relevant only if start or stop are array-like. By default (0), the samples will be along a new axis inserted at the beginning. Use -1 to get an axis at the end.

**Return Value:** There are num equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop) (depending on whether endpoint is True or False). Step is also returned if retstep is True.

---

In [6]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

`np.random.randint()`: It returns random integers from low (inclusive) to high (exclusive).

---

`numpy.random.randint(int low, int high=None, Tuple size=None, int dtype=np.int)`

**Description:** Return random integers from low (inclusive) to high (exclusive).

**Parameters:**

`low`: Lowest (signed) integers to be drawn from the distribution (unless high=None, in which case this parameter is one above the highest such integer).

`high`: If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None). If array-like, must contain integer values.

`size`: Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn.

`dtype`: Desired dtype of the result.

**Return Value:** Size-shaped array of random integers from the appropriate distribution, or a single such random int if size not provided.

---

In [7]:
np.random.randint(0, 100, 10)

array([96, 88, 30, 51, 55,  8,  8, 97, 43, 47])

## Useful Array Operations

NumPy also performs aggregation functions. In addition to `min`, `max`, and `sum`, you can easily run `mean` to get the average, `prod` to get the result of multiplying the elements together, `std` to get the standard deviation, and more.

In [8]:
arr = np.array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [9]:
arr.max()

95

In [10]:
arr.argmax()

0

In [11]:
arr.min()

9

In [12]:
arr.argmin()

7

In [13]:
arr.mean()

60.8

In [14]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

## Indexing and Slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.

---

`numpy.reshape(Array-like a, Tuple newshape, char order='C')`

**Description:** Gives a new shape to an array without changing its data.

**Parameters:**

`a`: Array to be reshaped.

`newshape`: The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

`order`: Read the elements of a using this index order, and place the elements into the reshaped array using this index order. ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of indexing. ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

**Return Value:** It returns the reshaped array that will be a new view object if possible; otherwise, it will be a copy. Note there is no guarantee of the memory layout (C- or Fortran- contiguous) of the returned array.

---

In [15]:
mat = np.arange(0, 40).reshape(4, 10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [16]:
mat[2, 7]

27

In [17]:
mat[:, 1]

array([ 1, 11, 21, 31])

In [18]:
mat[3, :]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [19]:
mat[1:3, 2:7]

array([[12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26]])