# Numpy Basics

NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

[NumPy: The absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)

## Importing

To access NumPy and its functions import it in your Python code like this:

In [1]:
import numpy as np

We shorten the imported name to np for better readability of code using NumPy. This is a widely adopted convention that you should follow so that anyone working with your code can easily understand it.

## Creating Arrays

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

### How to create a basic array

`np.array()`: To create a NumPy array, you can use this function:

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

### Other methods to create arrays

`np.zeros()`: Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [3]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

`np.ones()`: Or an array filled with 1’s:

In [4]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

`np.arange()`: You can create an array with a range of elements:

In [5]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`np.linspace()`: You can create an array with values that are spaced linearly in a specified interval:

In [6]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

`np.random.randint()`: It returns random integers from low (inclusive) to high (exclusive).

In [7]:
np.random.randint(0, 100, 10)

array([96, 88, 30, 51, 55,  8,  8, 97, 43, 47])

## Useful Array Operations

NumPy also performs aggregation functions. In addition to `min`, `max`, and `sum`, you can easily run `mean` to get the average, `prod` to get the result of multiplying the elements together, `std` to get the standard deviation, and more.

In [8]:
arr = np.array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [9]:
arr.max()

95

In [10]:
arr.argmax()

0

In [11]:
arr.min()

9

In [12]:
arr.argmin()

7

In [13]:
arr.mean()

60.8

In [14]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

## Indexing and Slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [15]:
mat = np.arange(0, 40).reshape(4, 10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [16]:
mat[2, 7]

27

In [17]:
mat[:, 1]

array([ 1, 11, 21, 31])

In [18]:
mat[3, :]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [19]:
mat[1:3, 2:7]

array([[12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26]])